/*
 *    @(#)helper.h 1.3 1/22/92 16:10:18 [1/26/92] (c)IBM Corp. 1992
 *
 * Adapted from the book
 *   Class Construction in C and C++, Object Oriented Fundamentals
 *   by Roger Sessions, Copyright (c) 1992 Prentice Hall.
 * Reprinted with permission.
 */

/* File: helper.h */

#ifndef HELPER_FILE
#define HELPER_FILE

#include <somobj.h>
void shouldHaveOverridden(SOMObject *thisObject, char *methodName);
#endif

